
title: My Resume
url: ''
baseurl: '/online-cv' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: HIRDESH ARORA
tagline: STUDENT DEVELOPER
pic: P15BD1A1221.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: arora.hirdesh17@gmail.com
phone: +91-7207833375
website: facebook.com/hirdesh.arora.3
linkedin: hirdesh-arora-1ab67b143/
github: hirdesh17
twitter: '@Mindblower'



# Tracker
analytics: UA-83979019-1
#Update all the sections by editing the files inside _includes folder.
